## < All Credits Goes To DarkBoy For Making This Bot > ##
## Main bot Config ##
mainprefix: 's!' # Main Prefix 
token: 'NzQzNjk4MjI5MjI4NzMyNDM4.XzYc8w.5UYegtwhk2UgFedhPoBRwBVza-U' # Token of your bot
status: 'testing rn' # ur bot status
## Join Support Guild: https://discord.gg/6KYRXQC  ##
